chococookie-lol/BARAM

- client/.eslintrc.json
- #5 
- `.eslintrc.json`의 `next/babel`을 `next`로 수정
> fix: eslint 오류 수정 (Close #5)

- deploy-client.sh
> fix: deploy 스크립트 오류 수정

- deploy-client.sh
- deploy.sh
- #3
- #8
- deploy 스크립트 yarn install 추가
> hotfix: deploy 스크립트 수정

- client/.eslintrc.json
- client/next.config.js
- client/package.json
- client/pages/_app.tsx
- client/styles/GlobalThemeContext.tsx
- client/styles/theme.ts
- client/tsconfig.json
- client/yarn.lock
- #18 
- `@emotion/react` 설치
- 라이트 테마 선언
- 전역 테마 Context 구현
- GlobalThemeContext
- GlobalThemeProvider
- useGlobalTheme
> FE 전역 테마 설정

- client/components/ChampionPic/index.tsx
- client/next.config.js
- #23 
- images remote pattern에 leaugeoflegends.com 추가
- 챔피언 초상화 구현
> FE 챔피언 초상화 구현

- client/components/Button/index.tsx
- #27 
- 버튼 구현
- 내부 텍스트 지정 가능
```ts
<Button
onClick={() => {
// Something to do when button clicked
}}
width={'100px'} // optional
>
전적 검색
</Button>
```
> 전적 버튼 구현 (Close #27)

- client/components/Percentage/index.tsx
- client/components/Percentage/style.ts
- #29 
- Percent 구현
```ts
<Percentage
backgroundColor={context.theme.background}
foregroundColor={context.theme.accent1}
textColor={context.theme.foreground}
value={0.1}
/>
```
> FE 퍼센트 바 구현

- client/components/Doughnut/index.tsx
- client/components/Doughnut/pathHelper.ts
- client/components/Doughnut/style.ts
- client/pages/index.tsx
- #25 
- Doughnut 구현
```ts
<Doughnut
label={['마법', '물리', '고정']}
val={[3123, 1231, 100]}
color={['skyblue', 'orange', 'grey']}
title="딜 유형"
size={100}
/>
```
> FE Pie chart 구현

- client/.eslintrc.json
- server/src/matches/matches.controller.spec.ts
- server/src/summoners/summoners.controller.spec.ts
> Eslint 설정 오류 수정 및 서버 테스트 수정 (Close #37)

- client/styles/theme.ts
- #46
- background, foreground 색상 서로 바꾸기
> hotfix: theme 수정 (Close #46)

- client/components/Percentage/index.tsx
- client/components/PercentageStatistics/index.tsx
- client/components/PercentageStatistics/style.ts
- #43
- 퍼센트 통계 컴포넌트 작성
```tsx
<PercentageStatistics
dealtPercent={0.45}
healPercent={0}
damagedPercent={0.42}
deathPercent={0.3}
/>
```
> feat: 퍼센트 통계 컴포넌트 작성 (Close #43)

- client/components/SummonerProfilePic/index.tsx
- #51
- SummonerProfilePic
```ts
<SummonerProfilePic version={'12.13.1'} id={1000} width={100} height={100} />
```
> FE SummonerProfilePic 구현

- client/components/RelativeBar/index.tsx
- client/components/RelativeBar/style.ts
- #42 
- RelativeBar 구현
```ts
<RelativeBar
label={'딜'}
average={5000}         // 기준이 되는 값 (평균)
value={8000}           // 표시할 값
maxOffset={5000}       // 값의 범위
foregroundColor={context.theme.foreground}
positiveColor={context.theme.accent1}
negativeColor={context.theme.red3}
textColor={context.theme.background}
/>
```
위와 같이 정의 했을 경우, 표현 가능한 값의 범위는 `0`~`10000` 입니다.
> FE RelativeBar 구현

- client/components/ChallengeIcon/index.tsx
- #53 
- ChallengeIcon
```ts
<ChallengeIcon
id={101000}
tier={'BRONZE'}
label={'도전과제'}
value={1234}
width={282}
height={305}
/>
```
> FE Challenges 컴포넌트 구현

- client/styles/theme.ts
> Global theme 색 추가

- client/components/PercentageStatistics/index.tsx
- client/components/PercentageStatistics/style.ts
- #61 
- 색상 옵션 추가
```tsx
<PercentageStatistics
dealtPercent={0.45}
dealtAmount={3214}
healPercent={0}
healAmount={32}
damagedPercent={0.42}
damagedAmount={2367}
deathPercent={0.3}
deathAmount={4}
color={{ foreground: theme.background, background: theme.foreground }}
/>
```
> feat: PercentageStatistics 색상 옵션 추가

- client/components/ItemIcon/index.tsx
- #67
- ItemIcon 구현
```ts
<ItemIcon id={1001} version={'12.23.1'} width={100} height={100} />
```
> ItemIcon 구현

- client/components/SummonerStatCard/index.tsx
- client/components/SummonerStatCard/style.ts
- #49 
- 소환사 통계 컴포넌트 작성
```tsx
<SummonerStatCard
winRate={winRate}
kda={kda}
camp={camp}
gameContribution={avgGameContribution}
/>
```
> 소환사 통계 컴포넌트 작성

- client/components/ItemStrip/index.tsx
- #69
- ItemStrip
```ts
<ItemStrip
items={[6670, 6670, 6670, 6670, 0, 0]}
version={'12.23.1'}
width={100}
height={100}
/>
```
> FE ItemStrip 구현

- client/styles/theme.ts
> fix: Global theme 오타 수정

- client/components/SpellIcon/index.tsx
- client/components/SpellStrip/index.tsx
- #73
- SpellIcon
```ts
<SpellIcon name={'SummonerExhaust'} version={'12.23.1'} width={100} height={100} />
```
- SpellStrip
```ts
<SpellStrip spells={['SummonerExhaust', '', '']} version={'12.23.1'} width={100} height={100} padding={3} direction={'vertical'}/>
```
> FE Spell component 구현

- client/components/Button/index.tsx
- client/components/SummonerProfileCard/index.tsx
- client/components/SummonerProfileCard/style.ts
- #66 
- 소환사 정보 카드 컴포넌트 작성
- 버튼 FG, BG 수정
```tsx
<SummonerProfileCard
profileIconId={5131}
summonerName={'소환사 이름'}
summonerLevel={123}
modifiedAt={0}
challenges={[
{ id: 101108, tier: 'GRANDMASTER', value: 231 },
{ id: 101101, tier: 'CHALLENGER', value: 231 },
{ id: 101106, tier: 'MASTER', value: 231 },
]}
/>
```
> 소환사 정보 카드 컴포넌트 작성

- client/components/RuneIcon/index.tsx
- client/components/RuneIcon/style.ts
- #75
- 주룬
```ts
<RuneIcon
name={'DarkHarvest'}
category={'Domination'}
width={100}
height={100}
/>
```
- 보조룬
```ts
<RuneIcon name={'7200_Domination'} width={100} height={100} />
```
> FE Rune 구현

- client/styles/theme.ts
- client/utils/color.ts
- #78
- 전역 색상 추가
- 테마 색상 전역 변수 참조
> feat: 전역 색상 추가

- client/components/ItemStrip/index.tsx
- client/components/SpellStrip/index.tsx
- #83
- SpellStrip 수정
- 첫번째 child 마진 제거
- flex -> inline
- ItemStrip 수정
- 첫번째 child 마진 제거
- flex -> inline
- direction 옵션 추가
> 컴포넌트 레아이웃 수정

- client/components/RelativeStatistics/index.tsx
- #80
- RelativeStatistics
```ts
<RelativeStatistics
dealAverage={3000}
dealMaxOffset={1000}
dealValue={2600}
goldAverage={13000}
goldMaxOffset={4000}
goldValue={16000}
deathAverage={12}
deathMaxOffset={10}
deathValue={4}
csAverage={100}
csMaxOffset={50}
csValue={56}
/>
```
> feat: RelativeStatistics 구현

- client/components/PercentageStatistics/index.tsx
- client/components/PercentageStatistics/style.ts
- #86
- padding 옵션 추가
- 레이아웃 수정
> PercentageStatistics 레이아웃 수정

- client/tsconfig.json
> build: global.d.ts 추가

- client/components/SummonerProfileCard/index.tsx
- client/global.d.ts
- #89
- Challenge 인터페이스 수정 (BE에 맞도록)
- SummonerProfile 인터페이스 추가
> fix: Challenge 인터페이스 수정

- client/components/RuneIcon/index.tsx
- client/components/RuneIcon/style.ts
> feat: RuneIcon padding 제거

- client/components/GameSlot/helper.ts
- client/components/GameSlot/index.tsx
- client/components/GameSlot/style.ts
- #60
- GameSlot 구현
```ts
<GameSlot
matchData={match}
puuid={'puuid'}
dealAverage={0}
dealMax={0}
deathAverage={0}
deathMax={0}
goldAverage={0}
goldMax={0}
csAverage={0}
csMax={0}
/>
```
> feat: GameSlot 구현

- client/styles/globals.css
> feat: 페이지 min width 설정

- client/components/SummonerProfileCard/index.tsx
- client/utils/time.ts
- #102
- epoch time을 상대시간으로 표시하도록 수정
> feat: 상대 시간 표시

- client/.env.development
- client/next.config.js
- #110 
- 모두 `/api`로 통일
- env 수정
- dev 모드에서는 `rewrite`기능으로 프록시
- prod 모드에서는 nginx가 프록시
> feat: dev, prod api 주소 통일

- client/global.d.ts
- client/pages/summoners/[summonerName].tsx
- server/src/summoners/summoners.service.ts
- #103 
- 소환사 정보에 `puuid` 추가 (ERD 수정)
- 서버 응답 수정된 ERD에 맞춰 수정
- GameSlot 추가
> 검색 페이지에 GameSlot 추가 및 ERD 수정 반영

- client/components/ChallengeIcon/index.tsx
- client/components/ChampionPic/index.tsx
- client/components/GameSlot/helper.ts
- client/components/GameSlot/index.tsx
- client/components/ItemIcon/index.tsx
- client/components/ItemStrip/index.tsx
- client/components/RuneIcon/index.tsx
- client/components/SpellIcon/index.tsx
- client/components/SpellStrip/index.tsx
- client/components/SummonerProfileCard/index.tsx
- client/components/SummonerProfilePic/index.tsx
- client/utils/ddragon.ts
- #114
- Component에 ddragon api 적용
- ChallengeIcon
- ChampionPic
- ItemIcon
- ItemStrip
- RuneIcon
- SpellIcon
- SummonerProfilePic
- SummonerProfileCard
- GameSlot
- ddragon api 수정
- base url 추가
- default placeholder 추가 (임시)
> ddragon api component에 적용

- client/components/Percentage/index.tsx
- client/components/Percentage/style.ts
- client/components/PercentageStatistics/style.ts
- #97
- 레이아웃 수정
- 텍스트, 레이블 vertical center
- 0 퍼센트 처리
- 소수점 고정
> FE Percentage, PercentageStatistics 수정

- client/components/Doughnut/pathHelper.ts
- client/components/Doughnut/style.ts
- #118
- Doughnut
- transition을 scale에만 적용
- 100%인 경우 처리
> FE Doughnut 수정

- client/global.d.ts
- server/src/matches/matches.service.ts
- #124
- gold, cs 추가
- 각 분야별 max, average 추가
> feat: matches contribution 수정

- client/components/SummonerStatCard/style.ts
- #131
- SummonerStatCard 내부 선택 불가하도록 수정
> fix: SummonerStatCard 내부 선택 불가 (Close #131)

- client/components/RelativeBar/index.tsx
> fix: RelativeBar 최소값 지정 (Close #125)

- server/src/riot.api/interface/index.ts
- server/src/riot.api/interface/riot.challenge.interface.ts
- server/src/riot.api/riot.api.service.ts
- server/src/summoners/schemas/summoner.schema.ts
- server/src/summoners/summoners.controller.ts
- server/src/summoners/summoners.module.ts
- server/src/summoners/summoners.service.ts
- #141
- GET /summoners/:summonerName 구현
- POST /summoners/:summonerName 구현
- `userName`을 `summonerName`으로 수정
> Summoner API 구현

- client/global.d.ts
- server/src/matches/matches.service.ts
- #144
- 기여도를 participant.participation에 저장
> feat: match participation 추가

- client/components/GameSlot/index.tsx
- client/utils/matchStatistic.ts
- #153
- GameSlot 수정
- matchStatistic 수정
> fix: FE 기여도 직접 계산 제거

- client/components/GameSlotDetail/index.tsx
- client/components/PercentageBar/index.tsx
- #154 
- 딜 비중 퍼센트 바 구현
- 마우스 이벤트 작동 안함
> feat: PercentageBar 구현

- client/components/SummonerProfileCard/index.tsx
- client/global.d.ts
- client/pages/summoners/[summonerName].tsx
> fix: 최근 업데이트 날짜 표시 오류 수정

- server/src/matches/matches.service.ts
- server/src/matches/schemas/match.schema.ts
- #170
- match schema 재정의: collection 이름 변경 (match)
- id -> info.gameId 사용하도록 변경
> BE schema 수정

- client/utils/ddragon.ts
> fix: ddragon 기본 이미지 추가

- client/components/RelativeBar/index.tsx
> fix: 최소값이 50 넘어가지 않도록 수정 (Close #171)

- client/global.d.ts
- server/src/matches/matches.module.ts
- server/src/matches/matches.service.ts
- server/src/summoners/schemas/summoner.schema.ts
- #175
- match fetch시 polling 하도록 api 수정
> BE match fetch시 polling 하도록 api 수정

- server/src/app.module.ts
- server/src/matches/dtos/post-puuid.dto.ts
- server/src/matches/matches.controller.ts
- server/src/matches/matches.module.ts
- server/src/matches/matches.service.ts
- server/src/play/play.module.ts
- server/src/play/play.service.ts
- server/src/play/schemas/play.schema.ts
- #179 
- #172 
- Play 모듈 작성
- findMany
- 인덱스 `{ puuid: 1, matchId: -1 }` 를 통해 정렬
- create
- Match 모듈에서 Play 모듈 사용
> Play 추가 및 Match 정렬

- server/src/matches/matches.controller.ts
- #187 
- match controller 주석 제거
- console.log 제거
> hotfix: #187

- client/components/GameSlot/index.tsx
- client/components/ItemIcon/index.tsx
- client/components/ItemStrip/index.tsx
- client/components/RuneIcon/index.tsx
- client/components/SpellIcon/index.tsx
- client/components/SpellStrip/index.tsx
- client/states/ddragon.ts
- client/utils/ddragon.ts
- #189 
- selectorFamily 사용해서 json 관리 (기존 selector)
- versions selector 추가
- 기존 version selector는 최신 버전을 가지도록 수정
> feat: ddragon 버전 관리 (Close #189)

- client/components/Button/index.tsx
- client/components/SummonerProfileCard/index.tsx
- client/global.d.ts
- client/pages/summoners/[summonerName].tsx
- client/utils/api.ts
- client/utils/matchStatistic.ts
- #183
- db에 summoner 정보 없을시 자동으로 fetch
- 전적 갱신 버튼 기능 구현
- 더보기 버튼 기능 구현
> FE /summoners/:summonerName api 적용

- server/src/matches/matches.service.ts
- server/src/play/play.service.ts
- server/src/play/schemas/play.schema.ts
- #195
- Play 정렬 게임 생성 시간으로 변경
> fix: play 정렬 게임 생성 시간 기준으로 변경 (Close #195)

- client/components/GameSlot/index.tsx
> fix: GameSlot 아이템 버그 수정 (Close #198)

- client/components/GameSlot/index.tsx
- client/components/GameSlot/style.ts
- #190
- nth-child 제거
- 각각 width 설정
> fix: FE GameSlot nth-child 대체 (Close #190)

- client/assets/downArrow.svg
- client/components/GameSlot/index.tsx
- client/components/GameSlot/style.ts
- #200
- downArrow.svg 추가
- GameSlot 펼치는 화살표 추가
> FE 펼치는 화살표 추가

- client/components/SummonerStatCard/index.tsx
- client/global.d.ts
- client/pages/summoners/[summonerName].tsx
- client/utils/matchStatistic.ts
- server/src/matches/matches.service.ts
- server/src/matches/schemas/match.schema.ts
- #207
- 총 기여도 점수 계산해서 contributionRank에 순위 저장
> ContributionRank 구현

- client/components/ItemIcon/index.tsx
- client/components/ItemStrip/index.tsx
- client/utils/ddragon.ts
- #218
-  itemIcon의 기본값을 DEFAULT_PLACEHOLDER로 변경
- DEFAULT_PLACEHOLDER_GRAY 추가
> fix: FE itemIcon의 기본값을 DEFAULT_PLACEHOLDER로 변경

- server/src/matches/matches.service.ts
- #216
- challenges는 불안정하므로 participant의 deaths를 사용
> BE match service death

- client/components/GameSlot/index.tsx
- client/components/GameSlot/style.ts
- #214
- GameSlotTable 수정
- rank 표시 추가
- column 넓이 조절
> FE GameSlotTable 수정

- client/components/GameSlot/index.tsx
- client/utils/time.ts
> feat: 날짜 표시 (Close #221)

- client/pages/_document.tsx
- client/styles/globals.css
> feat: font 적용

- client/components/SummonerStatCard/index.tsx
- #228
- 평균 게임 기여도 순위 precision 고정
> fix: 평균 게임 기여도 순위 precision 고정 (Close #228)

- client/components/ChallengeIcon/index.tsx
- client/components/ChampionPic/index.tsx
- client/components/Doughnut/index.tsx
- client/components/Doughnut/path.ts
- client/components/GameSlot/index.tsx
- client/components/ItemIcon/index.tsx
- client/components/ItemStrip/index.tsx
- client/components/Logo/index.tsx
- client/components/PercentageStatistics/index.tsx
- client/components/RelativeBar/index.tsx
- client/components/RelativeStatistics/index.tsx
- client/components/RuneIcon/index.tsx
- client/components/SpellIcon/index.tsx
- client/components/SpellStrip/index.tsx
- client/components/SummonerProfilePic/index.tsx
- client/components/SummonerStatCard/index.tsx
- client/pages/summoners/[summonerName].tsx
- client/states/ddragon.ts
- client/utils/api.ts
- client/utils/ddragon.ts
- #234
- 불필요한 await 제거
- 함수
- export 는 선언과 동시에
- 동사형 이름 사용
- 파일 내 선언 순서 조정 
1. 상수 선언
2. 인터페이스
3. 함수 (중요도 순)
- 파일명 간결하게 수정 (xxxhelper -> xxx)
> refactor: await, 함수, 순서, 파일명

- server/src/summoners/summoners.controller.spec.ts
- server/src/summoners/summoners.controller.ts
- server/src/summoners/summoners.service.ts
- server/src/summoners/test/summoners.controller.spec.ts
- server/src/summoners/test/summoners.mock.ts
- server/src/summoners/test/summoners.service.spec.ts
- #242 
- SummonerController 테스트 작성
- SummonerService 테스트 작성
- Summoner에서 Match 레거시 제거
> 소환사 테스트 작성

- client/pages/summoners/[summonerName].tsx
- #211
- 소환사가 없을 때 표시
- 소환사가 없을 때 표시하는 컴포넌트는 간단하게 구현함
> fix: FE 소환사가 없을 때 처리 (Close #211)

- client/components/Percentage/index.tsx
> feat: 최대 퍼센트 옵션 추가

- client/pages/summoners/[summonerName].tsx
- #249
- 더보기 응답이 403일 경우(exception을 throw 할 경우) get 요청을 보내서 받아온 (db에 저장되어 있는) 정보를 populate 하도록 변경
> 더보기 응답이 403일 경우 처리

- client/components/GameSlot/GameSlotContext.tsx
- client/components/GameSlot/index.tsx
- client/components/PercentageStatistics/index.tsx
- client/global.d.ts
- #254  
위 사진과 같이 해당 경기에서 가장 딜 혹은 탱을 많이 한 사람을 기준으로 최대값 결정.
> 경기의 딜 혹은 탱 최대값을 기준으로 Percentage 수정

- server/src/matches/matches.service.ts
- #269
- 실제로 업데이트가 되지 않아서 생긴 버그, 타임스탬프만 수정해야 하므로 수동으로 현재시간을 넣어줬다.
> hotfix: Summoner 업데이트 안되는 버그

- server/src/matches/matches.service.ts
> hotfix: 오타 수정 (Close #272)

- client/global.d.ts
- server/src/matches/matches.service.ts
- server/src/summoners/schemas/summoner.schema.ts
- server/src/summoners/test/summoners.mock.ts
- #264
- createdAt 추가, 갱신 요청시 updatedAt와 비교
> fix: 새로운 summoner 갱신 가능하게 변경

- client/pages/summoners/[summonerName].tsx
- #275
- setInterval 대신 setTimeout 사용
> fix: polling시 중복 요청 방지

- client/components/ChallengeIcon/index.tsx
- client/components/ChampionPic/index.tsx
- client/components/GameSlot/index.tsx
- client/components/GameSlot/style.ts
- client/components/ItemIcon/index.tsx
- client/components/LazyImage/index.tsx
- client/components/RuneIcon/index.tsx
- client/components/SpellIcon/index.tsx
- client/components/SpellStrip/index.tsx
- client/components/SummonerProfilePic/index.tsx
- #281
- Image를 wrap하는 LazyImage component 생성
```
<LazyImage
innerCss={wrapped Image에 적용할 style}
src={src}
width={width}
height={height}
alt={alt}
load={false면 transition 하지 않음}
/>
```
- onload에 css transition 해줌
> 이미지 lazyload animation

- client/pages/summoners/[summonerName].tsx
- #288
- '로딩중' 표시 결정 하는 state를 동기적으로 설정
- onClick 함수 분리
> FE 더보기/갱신 요청시 바로 UI에 적용 안되는 버그

- client/components/SearchBar/style.ts
> Input bar 높이 iOS 대응

- server/src/matches/matches.service.ts
- server/src/play/play.service.ts
-  #284
- API 승인으로 인해 최소 업데이트, 조회 단위를 10개로 수정
> 조회, 업데이트를 10 경기 단위로 수정

- client/components/ItemIcon/index.tsx
- client/components/LazyImage/index.tsx
- #281 
- Placeholder 사용하도록 수정
> next/Image placeholder 사용

- client/components/SpellStrip/index.tsx
- #295 
- spellStrip layout 버그 픽스
> hotfix: spellStrip layout

- client/pages/summoners/[summonerName].tsx
- #305 
- 검색 된 소환사 이름을 표시하도록 수정
> Title 소환사 이름 버그 수정

- client/components/GameSlot/GameSlotContext.tsx
- client/components/GameSlot/index.tsx
- client/components/Percentage/index.tsx
- client/components/Percentage/style.ts
- client/components/PercentageStatistics/index.tsx
- client/global.d.ts
- #297
- PercentageMax -> GameContribution (PercentageMax 포함)
- Percentage에 scale 변수 추가: bar width를 실제 값에 맞게 조정
> FE: Percentage Bar 최대값 문제

- .github/workflows/client-ci.yml
- .github/workflows/client-deploy.yml
- .github/workflows/server-ci.yml
- .github/workflows/server-deploy.yml
> CI 캐싱 및 CD 수정

- .github/workflows/client-ci.yml
- .github/workflows/server-ci.yml
> 🚑 hotfix: CI 오류 수정

- client/components/GameSlot/index.tsx
- client/components/GameSlot/style.ts
> FE GameSlot에서 소환사 이름 클릭시 페이지 이동

- client/pages/summoners/[summonerName].tsx
- #240 
- 백엔드 에러가 났을 때 프론트에서 표시
> feat: DDragon 서버가 응답하지 않을 경우 처리

- .github/workflows/client-ci.yml
- .github/workflows/install-dependency.yml
- .github/workflows/server-ci.yml
- #346
- 의존성 설치와 나머지 CI 분리
https://github.com/chococookie-lol/BARAM/blob/c4048bbb52c205a9fd624eee6660b62273d2b95e/.github/workflows/install-dependency.yml#L1-L14
- 캐시를 수동으로 저장하도록 수정
https://github.com/chococookie-lol/BARAM/blob/c4048bbb52c205a9fd624eee6660b62273d2b95e/.github/workflows/install-dependency.yml#L36-L43
- 의존성 설치를 제외한 나머지 CI 병렬 처리
- Server CI - Lint
https://github.com/chococookie-lol/BARAM/blob/c94dc1d961b98caa69fe9e3a836e825c481d2b77/.github/workflows/server-ci.yml#L18-L45
- Server CI - Test
https://github.com/chococookie-lol/BARAM/blob/c94dc1d961b98caa69fe9e3a836e825c481d2b77/.github/workflows/server-ci.yml#L47-L74
- Server CI - Build
https://github.com/chococookie-lol/BARAM/blob/c94dc1d961b98caa69fe9e3a836e825c481d2b77/.github/workflows/server-ci.yml#L76-L103
> CI 병렬 처리 및 분리

- .github/workflows/install-dependency.yml
- #346
- default path가 server로 지정되어있던 문제 수정
> hotfix: 의존성 설치 workflow 오류 수정

- .github/workflows/client-ci.yml
- .github/workflows/install-dependency.yml
- .github/workflows/server-ci.yml
- #346
- 의존성 설치 부분에서 working-directory를 지정하지 않아 생긴 문제 해결
> hotfix: 의존성 설치 오류 해결

- .github/workflows/client-ci.yml
- .github/workflows/install-dependency.yml
- .github/workflows/server-ci.yml
> [v1.0.1-hotfix.2] 작업사항
